import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import Link from "next/link";
import { redirect } from "next/navigation";
import Navbar from "@/components/Navbar";

import hero from "/public/hero.png";

import { Button } from "@/components/ui/button";
import ExplainerSection from "@/components/ExplainerSection";
import PricingSection from "@/components/PricingSection";
import Footer from "@/components/Footer";

import Bicker from "@/components/Ticker";

export default async function Index() {

  const supabase = createServerComponentClient({ cookies });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (user) {
    return redirect("/overview");
  }

  return (
    <div className="absolute w-[100.01%] overflow-x-clip">
      <div className="relative fixed top-0 inset-0">
        <Navbar />
      </div>
      <div className="h-screen">
        <div className="flex flex-col items-center pt-12 bg-white h-screen">
          <div className="flex flex-col items-center gap-8 p-8 max-w-6xl w-[95%]">
            <div className="flex flex-col space-y-4 w-full">
              <h1 className="text-[64px] mx-6 lg:mx-20 xl:mx-32 text-center leading-[4.5rem] font-[800]">
                Professional AI Headshots in minutes.
              </h1>
              <p className="-translate-y-1 mx-16 md:mx-36 lg:mx-44 xl:mx-64 text-center bg-gradient-to-r from-cyan-400 via-sky-00 to-blue-400 bg-clip-text text-transparent font-medium text-[22px]">
                Elevate your online presence with HD headshots generated by our AI.
                Ideal for social profiles, resumes, and professional portfolios.
              </p>
              <div className="flex justify-center">
                <div className="relative">
                  <Link href="/login">
                    <div
                      className="absolute -inset-[.15rem] hover:-inset-[.1rem] rounded-lg bg-gradient-to-r from-cyan-500 via-orange-600 to-red-600 opacity-50 blur"
                    ></div>
                    <Button
                      className="-mt-2 relative bg-sky-500 hover:bg-sky-600 transition ease-in duration-200 flex w-auto p-5 rounded-full items-center justify-center rounded-full text-white font-semibold text-lg"
                    >
                      Create yours
                      <svg className="ml-2 -mr-1" width="24px" height="24px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="m11 4-.5-1-.5 1-1 .125.834.708L9.5 6l1-.666 1 .666-.334-1.167.834-.708zm8.334 10.666L18.5 13l-.834 1.666-1.666.209 1.389 1.181L16.834 18l1.666-1.111L20.166 18l-.555-1.944L21 14.875zM6.667 6.333 6 5l-.667 1.333L4 6.5l1.111.944L4.667 9 6 8.111 7.333 9l-.444-1.556L8 6.5zM3.414 17c0 .534.208 1.036.586 1.414L5.586 20c.378.378.88.586 1.414.586s1.036-.208 1.414-.586L20 8.414c.378-.378.586-.88.586-1.414S20.378 5.964 20 5.586L18.414 4c-.756-.756-2.072-.756-2.828 0L4 15.586c-.378.378-.586.88-.586 1.414zM17 5.414 18.586 7 15 10.586 13.414 9 17 5.414z"/></svg>
                    </Button>
                  </Link>
                </div>
              </div>
              <div className="w-full flex justify-center">
                <p className="text-sm text-gray-500 italic -mt-2">
                  Trusted by professionals worldwide. Quick and efficient.
                </p>
              </div>
            </div>
            <div className="w-full flex justify-center mt-8 lg:mt-4">
              <Bicker/>
            </div>
          </div>
        </div>
        <ExplainerSection />
        <PricingSection />
      </div>
    </div>
  );
}
